# Generated by Django 4.2 on 2023-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_newshippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshippingadress',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newshippingadress',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newshippingadress',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
